# Generated by Django 3.2.7 on 2021-10-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='유튜브 제목')),
                ('url', models.URLField(verbose_name='유튜브 url')),
            ],
        ),
    ]
