# Generated by Django 3.2.7 on 2021-10-02 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
