# Generated by Django 3.2.7 on 2021-10-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_remove_user_is_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
