# Generated by Django 3.2.7 on 2021-10-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Q&A게시판', 'verbose_name_plural': 'Q&A게시판'},
        ),
        migrations.AddField(
            model_name='board',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterModelTable(
            name='board',
            table='Q&A게시판',
        ),
    ]
