# Generated by Django 3.2.7 on 2021-10-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0002_auto_20211025_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='updated_at',
        ),
    ]
