# Generated by Django 3.2.7 on 2021-10-14 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0003_alter_board_writer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={},
        ),
        migrations.AlterModelTable(
            name='board',
            table=None,
        ),
    ]
