# Generated by Django 3.2.7 on 2021-10-31 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainerapp', '0002_registereduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registereduser',
            name='trainer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainerapp.trainer', verbose_name='등록된 트레이너'),
        ),
        migrations.RemoveField(
            model_name='registereduser',
            name='user',
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='등록한 일반인'),
        ),
    ]
