# Generated by Django 3.2.7 on 2021-11-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0004_auto_20211102_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'managed': False},
        ),
    ]
