# Generated by Django 3.2.7 on 2021-11-02 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0005_alter_trainer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={},
        ),
    ]
