# Generated by Django 3.2.7 on 2021-11-02 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainerapp', '0006_alter_trainer_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='user',
            new_name='member',
        ),
    ]
